#!/bin/bash
# Packforge - CLI tool for creating paedML OPSI packages

WORKBENCH="/var/lib/opsi/workbench"

banner() {
cat << 'EOF'

                      ______ ________
______________ _________  /____  __/___________________ _____
___  __ \  __ `/  ___/_  //_/_  /_ _  __ \_  ___/_  __ `/  _ \
__  /_/ / /_/ // /__ _  ,<  _  __/ / /_/ /  /   _  /_/ //  __/
_  .___/\__,_/ \___/ /_/|_| /_/    \____//_/    _\__, / \___/
/_/                                             /____/

EOF
}

do_create() {
    echo ""
    echo "--- Create OPSI Package ---"
    echo ""

    # Product ID
    while true; do
        read -p "Product ID (e.g. my-software): " product_id
        if echo "$product_id" | grep -qE '^[a-z0-9][a-z0-9-]*$'; then
            break
        fi
        echo "Invalid product ID. Use lowercase letters, numbers, and hyphens."
    done

    # Product name
    read -p "Product name [$product_id]: " product_name
    product_name="${product_name:-$product_id}"

    # Version
    read -p "Version [1.0]: " product_version
    product_version="${product_version:-1.0}"

    # Package version
    read -p "Package version [1]: " package_version
    package_version="${package_version:-1}"

    # Description
    read -p "Description: " description

    # Create directories
    package_dir="$WORKBENCH/$product_id"
    opsi_dir="$package_dir/OPSI"
    client_dir="$package_dir/CLIENT_DATA"

    if [ -d "$package_dir" ]; then
        echo ""
        echo "Directory already exists: $package_dir"
        read -p "Overwrite? (y/N): " overwrite
        if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
            echo "Aborted."
            return
        fi
    fi

    mkdir -p "$opsi_dir" "$client_dir"

    # Write control file
    cat > "$opsi_dir/control" << CTRL
[Package]
version: $package_version
depends:

[Product]
type: localboot
id: $product_id
name: $product_name
description: $description
advice:
version: $product_version
priority: 0
licenseRequired: False
productClasses:
setupScript: setup.ins
uninstallScript: uninstall.ins
updateScript:
alwaysScript:
onceScript:
customScript:
userLoginScript:
CTRL

    # Write setup.ins
    cat > "$client_dir/setup.ins" << SETUP
; setup script for $product_name
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar \$ProductId\$
Set \$ProductId\$ = "$product_id"

Message "Installing " + \$ProductId\$ + " ..."

; Add installation steps here
SETUP

    # Write uninstall.ins
    cat > "$client_dir/uninstall.ins" << UNINST
; uninstall script for $product_name
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar \$ProductId\$
Set \$ProductId\$ = "$product_id"

Message "Uninstalling " + \$ProductId\$ + " ..."

; Add uninstallation steps here
UNINST

    echo ""
    echo "Package created: $package_dir"
    echo "  OPSI/control"
    echo "  CLIENT_DATA/setup.ins"
    echo "  CLIENT_DATA/uninstall.ins"
    echo ""

    # Build
    if ! command -v opsi-makepackage > /dev/null 2>&1; then
        echo "ERROR: opsi-makepackage not found."
        return
    fi

    echo "Building package..."
    if opsi-makepackage -q --no-md5 -d "$package_dir"; then
        echo "Build successful."
    else
        echo "Build failed."
        return
    fi

    # Install
    if ! command -v opsi-package-manager > /dev/null 2>&1; then
        echo "ERROR: opsi-package-manager not found."
        return
    fi

    echo "Installing package..."
    if opsi-package-manager -i "$package_dir"; then
        echo "Package installed."
    else
        echo "Install failed."
    fi
}

do_list() {
    echo ""
    echo "--- Packages in Workbench ---"
    echo ""

    if [ ! -d "$WORKBENCH" ]; then
        echo "Workbench not found: $WORKBENCH"
        return
    fi

    found=0
    for dir in "$WORKBENCH"/*/; do
        if [ -f "${dir}OPSI/control" ]; then
            echo "  $(basename "$dir")"
            found=1
        fi
    done

    if [ "$found" -eq 0 ]; then
        echo "No packages found."
    fi
}

# Main
banner

while true; do
    echo "  [1] Create package"
    echo "  [2] List packages"
    echo "  [0] Exit"
    echo ""
    read -p "Select: " choice

    case "$choice" in
        1) do_create ;;
        2) do_list ;;
        0) echo "Bye."; exit 0 ;;
        *) echo "Invalid choice." ;;
    esac
done
