#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Packforge - CLI tool for creating paedML OPSI packages."""

from __future__ import print_function

import os
import sys
import subprocess
import re


WORKBENCH = "/var/lib/opsi/workbench"

BANNER = r"""
                      ______ ________
______________ _________  /____  __/___________________ _____
___  __ \  __ `/  ___/_  //_/_  /_ _  __ \_  ___/_  __ `/  _ \
__  /_/ / /_/ // /__ _  ,<  _  __/ / /_/ /  /   _  /_/ //  __/
_  .___/\__,_/ \___/ /_/|_| /_/    \____//_/    _\__, / \___/
/_/                                             /____/
"""

MENU = """\
  [1] Create package
  [2] List packages
  [0] Exit
"""

CONTROL_TEMPLATE = """\
[Package]
version: {package_version}
depends:

[Product]
type: localboot
id: {product_id}
name: {product_name}
description: {description}
advice:
version: {product_version}
priority: 0
licenseRequired: False
productClasses:
setupScript: setup.ins
uninstallScript: uninstall.ins
updateScript:
alwaysScript:
onceScript:
customScript:
userLoginScript:
"""

SETUP_TEMPLATE = """\
; setup script for {product_name}
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar $ProductId$
Set $ProductId$ = "{product_id}"

Message "Installing " + $ProductId$ + " ..."

; Add installation steps here
"""

UNINSTALL_TEMPLATE = """\
; uninstall script for {product_name}
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar $ProductId$
Set $ProductId$ = "{product_id}"

Message "Uninstalling " + $ProductId$ + " ..."

; Add uninstallation steps here
"""


def prompt(text, default=None):
    if default:
        text = "{} [{}]: ".format(text, default)
    else:
        text = "{}: ".format(text)
    if sys.version_info[0] >= 3:
        value = input(text).strip()
    else:
        value = raw_input(text).strip()
    return value if value else default


def validate_product_id(product_id):
    if not product_id:
        return False
    return bool(re.match(r'^[a-z0-9][a-z0-9\-]*$', product_id))


def cmd_exists(cmd):
    try:
        proc = subprocess.Popen(
            ["which", cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        proc.communicate()
        return proc.returncode == 0
    except OSError:
        return False


def build_package(package_dir):
    if not cmd_exists("opsi-makepackage"):
        print("ERROR: opsi-makepackage not found.")
        return False

    print("Building package...")
    proc = subprocess.Popen(
        ["opsi-makepackage", "-q"],
        cwd=package_dir,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    stdout, stderr = proc.communicate()

    if proc.returncode != 0:
        print("Build failed:")
        if stderr:
            print(stderr)
        return False

    if stdout:
        print(stdout)
    print("Build successful.")
    return True


def install_package(package_dir):
    if not cmd_exists("opsi-package-manager"):
        print("ERROR: opsi-package-manager not found.")
        return False

    print("Installing package...")
    proc = subprocess.Popen(
        ["opsi-package-manager", "-i", package_dir],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    stdout, stderr = proc.communicate()

    if proc.returncode != 0:
        print("Install failed:")
        if stderr:
            print(stderr)
        return False

    if stdout:
        print(stdout)
    print("Package installed.")
    return True


def do_create():
    print("\n--- Create OPSI Package ---\n")

    product_id = prompt("Product ID (e.g. my-software)")
    while not validate_product_id(product_id):
        print("Invalid product ID. Use lowercase letters, numbers, and hyphens.")
        product_id = prompt("Product ID")

    product_name = prompt("Product name", product_id)
    product_version = prompt("Version", "1.0")
    package_version = prompt("Package version", "1")
    description = prompt("Description", "")

    package_dir = os.path.join(WORKBENCH, product_id)
    opsi_dir = os.path.join(package_dir, "OPSI")
    client_dir = os.path.join(package_dir, "CLIENT_DATA")

    if os.path.exists(package_dir):
        print("\nDirectory already exists: {}".format(package_dir))
        overwrite = prompt("Overwrite? (y/N)", "N")
        if overwrite.lower() != "y":
            print("Aborted.")
            return

    for d in [opsi_dir, client_dir]:
        if not os.path.exists(d):
            os.makedirs(d)

    ctx = {
        "product_id": product_id,
        "product_name": product_name,
        "product_version": product_version,
        "package_version": package_version,
        "description": description or "",
    }

    with open(os.path.join(opsi_dir, "control"), "w") as f:
        f.write(CONTROL_TEMPLATE.format(**ctx))

    with open(os.path.join(client_dir, "setup.ins"), "w") as f:
        f.write(SETUP_TEMPLATE.format(**ctx))

    with open(os.path.join(client_dir, "uninstall.ins"), "w") as f:
        f.write(UNINSTALL_TEMPLATE.format(**ctx))

    print("\nPackage created: {}".format(package_dir))
    print("  OPSI/control")
    print("  CLIENT_DATA/setup.ins")
    print("  CLIENT_DATA/uninstall.ins\n")

    # Build
    if not build_package(package_dir):
        return

    # Install
    install_package(package_dir)


def do_list():
    print("\n--- Packages in Workbench ---\n")

    if not os.path.isdir(WORKBENCH):
        print("Workbench not found: {}".format(WORKBENCH))
        return

    packages = []
    for name in sorted(os.listdir(WORKBENCH)):
        control = os.path.join(WORKBENCH, name, "OPSI", "control")
        if os.path.isfile(control):
            packages.append(name)

    if not packages:
        print("No packages found.")
    else:
        for p in packages:
            print("  {}".format(p))


def main():
    print(BANNER)

    while True:
        print(MENU)
        choice = prompt("Select")

        if choice == "1":
            do_create()
        elif choice == "2":
            do_list()
        elif choice == "0":
            print("Bye.")
            break
        else:
            print("Invalid choice.")


if __name__ == "__main__":
    main()
