#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Packforge - CLI tool for creating paedML OPSI packages."""

from __future__ import print_function

import os
import sys
import argparse
import subprocess
import re


WORKBENCH = "/var/lib/opsi/workbench"

BANNER = r"""
                      ______ ________
______________ _________  /____  __/___________________ _____
___  __ \  __ `/  ___/_  //_/_  /_ _  __ \_  ___/_  __ `/  _ \
__  /_/ / /_/ // /__ _  ,<  _  __/ / /_/ /  /   _  /_/ //  __/
_  .___/\__,_/ \___/ /_/|_| /_/    \____//_/    _\__, / \___/
/_/                                             /____/
"""


CONTROL_TEMPLATE = """\
[Package]
version: {package_version}
depends:

[Product]
type: localboot
id: {product_id}
name: {product_name}
description: {description}
advice:
version: {product_version}
priority: 0
licenseRequired: False
productClasses:
setupScript: setup.ins
uninstallScript: uninstall.ins
updateScript:
alwaysScript:
onceScript:
customScript:
userLoginScript:
"""

SETUP_TEMPLATE = """\
; setup script for {product_name}
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar $ProductId$
Set $ProductId$ = "{product_id}"

Message "Installing " + $ProductId$ + " ..."

; Add installation steps here
"""

UNINSTALL_TEMPLATE = """\
; uninstall script for {product_name}
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar $ProductId$
Set $ProductId$ = "{product_id}"

Message "Uninstalling " + $ProductId$ + " ..."

; Add uninstallation steps here
"""


def prompt(text, default=None):
    if default:
        text = "{} [{}]: ".format(text, default)
    else:
        text = "{}: ".format(text)
    if sys.version_info[0] >= 3:
        value = input(text).strip()
    else:
        value = raw_input(text).strip()
    return value if value else default


def validate_product_id(product_id):
    if not product_id:
        return False
    return bool(re.match(r'^[a-z0-9][a-z0-9\-]*$', product_id))


def cmd_create(args):
    print(BANNER)

    product_id = args.product_id or prompt("Product ID (e.g. my-software)")
    while not validate_product_id(product_id):
        print("Invalid product ID. Use lowercase letters, numbers, and hyphens.")
        product_id = prompt("Product ID")

    product_name = args.name or prompt("Product name", product_id)
    product_version = args.version or prompt("Version", "1.0")
    package_version = prompt("Package version", "1")
    description = args.description or prompt("Description", "")

    package_dir = os.path.join(WORKBENCH, product_id)
    opsi_dir = os.path.join(package_dir, "OPSI")
    client_dir = os.path.join(package_dir, "CLIENT_DATA")

    if os.path.exists(package_dir):
        print("\nDirectory already exists: {}".format(package_dir))
        overwrite = prompt("Overwrite? (y/N)", "N")
        if overwrite.lower() != "y":
            print("Aborted.")
            return 1

    for d in [opsi_dir, client_dir]:
        if not os.path.exists(d):
            os.makedirs(d)

    ctx = {
        "product_id": product_id,
        "product_name": product_name,
        "product_version": product_version,
        "package_version": package_version,
        "description": description or "",
    }

    with open(os.path.join(opsi_dir, "control"), "w") as f:
        f.write(CONTROL_TEMPLATE.format(**ctx))

    with open(os.path.join(client_dir, "setup.ins"), "w") as f:
        f.write(SETUP_TEMPLATE.format(**ctx))

    with open(os.path.join(client_dir, "uninstall.ins"), "w") as f:
        f.write(UNINSTALL_TEMPLATE.format(**ctx))

    print("\nPackage created: {}".format(package_dir))
    print("  OPSI/control")
    print("  CLIENT_DATA/setup.ins")
    print("  CLIENT_DATA/uninstall.ins")

    build = prompt("\nBuild package now? (y/N)", "N")
    if build.lower() == "y":
        return cmd_build_path(package_dir)

    return 0


def cmd_build(args):
    package_dir = os.path.join(WORKBENCH, args.product_id)
    if not os.path.isdir(package_dir):
        print("Not found: {}".format(package_dir))
        return 1
    return cmd_build_path(package_dir)


def cmd_build_path(package_dir):
    control = os.path.join(package_dir, "OPSI", "control")
    if not os.path.isfile(control):
        print("No OPSI/control found in {}".format(package_dir))
        return 1

    print("Building package in {}...".format(package_dir))
    proc = subprocess.Popen(
        ["opsi-makepackage", "-q"],
        cwd=package_dir,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    stdout, stderr = proc.communicate()

    if proc.returncode != 0:
        print("Build failed:")
        if stderr:
            print(stderr)
        return 1

    if stdout:
        print(stdout)
    print("Build successful.")
    return 0


def cmd_install(args):
    package_dir = os.path.join(WORKBENCH, args.product_id)
    if not os.path.isdir(package_dir):
        print("Not found: {}".format(package_dir))
        return 1

    print("Installing {}...".format(args.product_id))
    proc = subprocess.Popen(
        ["opsi-package-manager", "-i", package_dir],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    stdout, stderr = proc.communicate()

    if proc.returncode != 0:
        print("Install failed:")
        if stderr:
            print(stderr)
        return 1

    if stdout:
        print(stdout)
    print("Package installed.")
    return 0


def cmd_list(args):
    if not os.path.isdir(WORKBENCH):
        print("Workbench not found: {}".format(WORKBENCH))
        return 1

    packages = []
    for name in sorted(os.listdir(WORKBENCH)):
        control = os.path.join(WORKBENCH, name, "OPSI", "control")
        if os.path.isfile(control):
            packages.append(name)

    if not packages:
        print("No packages found in workbench.")
    else:
        print("Packages in workbench:")
        for p in packages:
            print("  {}".format(p))

    return 0


def main():
    parser = argparse.ArgumentParser(
        prog="packforge",
        description="Packforge - create and manage paedML OPSI packages",
    )
    sub = parser.add_subparsers(dest="command")

    p_create = sub.add_parser("create", help="Create a new OPSI package")
    p_create.add_argument("product_id", nargs="?", help="Product ID")
    p_create.add_argument("-n", "--name", help="Product name")
    p_create.add_argument("-v", "--version", help="Product version")
    p_create.add_argument("-d", "--description", help="Description")

    p_build = sub.add_parser("build", help="Build an OPSI package")
    p_build.add_argument("product_id", help="Product ID")

    p_install = sub.add_parser("install", help="Install an OPSI package")
    p_install.add_argument("product_id", help="Product ID")

    sub.add_parser("list", help="List packages in workbench")

    args = parser.parse_args()

    if not args.command:
        print(BANNER)
        parser.print_help()
        return 0

    commands = {
        "create": cmd_create,
        "build": cmd_build,
        "install": cmd_install,
        "list": cmd_list,
    }

    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
