#!/bin/bash
# Packforge - CLI tool for creating paedML OPSI packages

WORKBENCH="/var/lib/opsi/workbench"

banner() {
cat << 'EOF'

                      ______ ________
______________ _________  /____  __/___________________ _____
___  __ \  __ `/  ___/_  //_/_  /_ _  __ \_  ___/_  __ `/  _ \
__  /_/ / /_/ // /__ _  ,<  _  __/ / /_/ /  /   _  /_/ //  __/
_  .___/\__,_/ \___/ /_/|_| /_/    \____//_/    _\__, / \___/
/_/                                             /____/

EOF
}

do_create() {
    echo ""
    echo "--- Create OPSI Package ---"
    echo ""

    # Product ID
    while true; do
        read -p "Product ID (e.g. my-software): " product_id
        if echo "$product_id" | grep -qE '^[a-z0-9][a-z0-9._-]*$'; then
            break
        fi
        echo "Invalid product ID. Use lowercase letters, numbers, hyphens, dots, underscores."
    done

    # Product name
    read -p "Product name [$product_id]: " product_name
    product_name="${product_name:-$product_id}"

    # Version
    read -p "Version [1.0]: " product_version
    product_version="${product_version:-1.0}"

    # Package version
    read -p "Package version [1]: " package_version
    package_version="${package_version:-1}"

    # Description
    read -p "Description: " description

    # Advice
    read -p "Advice (e.g. 'Requires .NET 4.8'): " advice

    # Priority
    read -p "Priority (-100 to 100) [0]: " priority
    priority="${priority:-0}"

    # --- Dependencies ---
    dep_blocks=""
    echo ""
    read -p "Add package dependencies? (y/N): " add_deps
    if [ "$add_deps" = "y" ] || [ "$add_deps" = "Y" ]; then
        if command -v whiptail > /dev/null 2>&1 && command -v opsi-package-manager > /dev/null 2>&1; then
            echo "Loading packages..."
            dep_pkg_list=$(LC_ALL=C opsi-package-manager -l 2>/dev/null | awk '/^   [a-z0-9]/ {print $1}')

            if [ -n "$dep_pkg_list" ]; then
                dep_count=$(echo "$dep_pkg_list" | wc -l)
                dep_lh=$dep_count
                if [ "$dep_lh" -gt 20 ]; then dep_lh=20; fi
                dep_h=$((dep_lh + 8))

                set --
                for dp in $dep_pkg_list; do
                    set -- "$@" "$dp" "" OFF
                done

                selected_deps=$(whiptail --checklist "Select dependencies (must be installed before this package)" $dep_h 60 $dep_lh "$@" 3>&1 1>&2 2>&3)
                selected_deps=$(echo "$selected_deps" | tr -d '"')

                for dep in $selected_deps; do
                    dep_blocks="$dep_blocks
[ProductDependency]
action: setup
requiredProduct: $dep
requiredStatus: installed
requirementType: before
"
                done
            fi
        else
            echo "whiptail or opsi-package-manager not found, skipping."
        fi
    fi

    # --- Create directories ---
    package_dir="$WORKBENCH/$product_id"
    opsi_dir="$package_dir/OPSI"
    client_dir="$package_dir/CLIENT_DATA"
    files_dir="$client_dir/files"

    if [ -d "$package_dir" ]; then
        echo ""
        echo "Directory already exists: $package_dir"
        read -p "Overwrite? (y/N): " overwrite
        if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
            echo "Aborted."
            return
        fi
    fi

    mkdir -p "$opsi_dir" "$client_dir" "$files_dir"

    # --- Write control file ---
    cat > "$opsi_dir/control" << CTRL
[Package]
version: $package_version
depends:

[Product]
type: localboot
id: $product_id
name: $product_name
description: $description
advice: $advice
version: $product_version
priority: $priority
licenseRequired: False
productClasses:
setupScript: setup.opsiscript
uninstallScript: uninstall.opsiscript
updateScript:
alwaysScript:
onceScript:
customScript:
userLoginScript:
CTRL

    # Append dependencies
    if [ -n "$dep_blocks" ]; then
        echo "$dep_blocks" >> "$opsi_dir/control"
    fi


    # --- Write setup.opsiscript ---
    cat > "$client_dir/setup.opsiscript" << 'SETUP'
; setup script for PRODUCTNAME
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar $ProductId$
DefVar $InstallDir$
DefVar $Setupfile$

Set $ProductId$ = EnvVar("PRODUCT_ID")
Set $InstallDir$ = "%ProgramFiles32Dir%\" + $ProductId$
Set $Setupfile$ = "%ScriptPath%\files\setup.exe"

Message "Installing " + $ProductId$ + " ..."

; Example: silent install from files/ directory
; Winbatch_Install

; Example: copy files
; Files_Install

; [Winbatch_Install]
; $Setupfile$ /S /D=$InstallDir$

; [Files_Install]
; copy -s "%ScriptPath%\files\*" "$InstallDir$"
SETUP
    sed -i "s/PRODUCTNAME/$product_name/g" "$client_dir/setup.opsiscript"

    # --- Write uninstall.opsiscript ---
    cat > "$client_dir/uninstall.opsiscript" << 'UNINST'
; uninstall script for PRODUCTNAME
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar $ProductId$
DefVar $InstallDir$
DefVar $UninstallProgram$

Set $ProductId$ = EnvVar("PRODUCT_ID")
Set $InstallDir$ = "%ProgramFiles32Dir%\" + $ProductId$
Set $UninstallProgram$ = $InstallDir$ + "\uninstall.exe"

Message "Uninstalling " + $ProductId$ + " ..."

; Example: silent uninstall
; Winbatch_Uninstall

; Example: remove directory
; Files_Uninstall

; [Winbatch_Uninstall]
; $UninstallProgram$ /S

; [Files_Uninstall]
; del -sf "$InstallDir$"
UNINST
    sed -i "s/PRODUCTNAME/$product_name/g" "$client_dir/uninstall.opsiscript"

    # --- Show result ---
    echo ""
    echo "Package created: $package_dir"
    echo ""
    echo "  $product_id/"
    echo "  ├── OPSI/"
    echo "  │   └── control"
    echo "  └── CLIENT_DATA/"
    echo "      ├── files/"
    echo "      │   └── (place installers here)"
    echo "      ├── setup.opsiscript"
    echo "      └── uninstall.opsiscript"
    echo ""
    echo "Place your installer files into CLIENT_DATA/files/:"
    echo ""
    printf '  SMB: \\\\%s\\opsi_workbench\\%s\\CLIENT_DATA\\files\\\n' "$(hostname -f)" "$product_id"
    echo "  SCP: scp <file> root@$(hostname -f):$files_dir/"
    echo ""
    read -p "Press ENTER when files are in place (or 's' to skip build)... " wait_input

    if [ "$wait_input" = "s" ] || [ "$wait_input" = "S" ]; then
        echo "Skipped build. Add files and build later."
        return
    fi

    # Show what's in CLIENT_DATA
    echo ""
    echo "Files in CLIENT_DATA:"
    ls -la "$client_dir"
    echo "Files in CLIENT_DATA/files:"
    ls -la "$files_dir"
    echo ""
    read -p "Continue with build and install? (y/N): " build_confirm
    if [ "$build_confirm" != "y" ] && [ "$build_confirm" != "Y" ]; then
        echo "Aborted."
        return
    fi

    # Build
    if ! command -v opsi-makepackage > /dev/null 2>&1; then
        echo "ERROR: opsi-makepackage not found."
        return
    fi

    echo "Building package..."
    if (cd "$package_dir" && opsi-makepackage --quiet --no-md5 --no-zsync); then
        echo "Build successful."
    else
        echo "Build failed."
        return
    fi

    # Find the built .opsi file
    opsi_file=$(ls -t "$package_dir"/*.opsi 2>/dev/null | head -1)
    if [ -z "$opsi_file" ]; then
        echo "ERROR: No .opsi file found after build."
        return
    fi

    # Install
    if ! command -v opsi-package-manager > /dev/null 2>&1; then
        echo "ERROR: opsi-package-manager not found."
        return
    fi

    echo "Installing package..."
    if LC_ALL=C opsi-package-manager -i "$opsi_file"; then
        echo "Package installed."
    else
        echo "Install failed."
    fi
}

do_remove() {
    echo ""
    echo "--- Remove OPSI Package ---"
    echo ""

    if ! command -v opsi-package-manager > /dev/null 2>&1; then
        echo "ERROR: opsi-package-manager not found. Is this the OPSI depot server?"
        return
    fi

    if ! command -v whiptail > /dev/null 2>&1; then
        echo "ERROR: whiptail not found."
        return
    fi

    echo "Loading packages..."
    pkg_list=$(LC_ALL=C opsi-package-manager -l 2>/dev/null | awk '/^   [a-z0-9]/ {print $1}')

    if [ -z "$pkg_list" ]; then
        echo "No packages found."
        return
    fi

    pkg_count=$(echo "$pkg_list" | wc -l)
    list_height=$pkg_count
    if [ "$list_height" -gt 20 ]; then list_height=20; fi
    height=$((list_height + 8))

    set --
    for pkg in $pkg_list; do
        set -- "$@" "$pkg" "" OFF
    done

    selected_pkgs=$(whiptail --checklist "Select packages to remove (SPACE=select, ENTER=confirm)" $height 60 $list_height "$@" 3>&1 1>&2 2>&3)

    if [ $? -ne 0 ] || [ -z "$selected_pkgs" ]; then
        echo "No packages selected."
        return
    fi

    selected_pkgs=$(echo "$selected_pkgs" | tr -d '"')

    echo ""
    echo "Packages to remove:"
    for pkg in $selected_pkgs; do
        echo "  $pkg"
    done

    echo ""
    read -p "Are you sure? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        return
    fi

    for pkg in $selected_pkgs; do
        echo "Removing $pkg..."
        if LC_ALL=C opsi-package-manager -r "$pkg" 2>/dev/null; then
            echo "  OK: $pkg removed."
        else
            echo "  FAILED: $pkg"
        fi

        # Clean up workbench directory if it exists
        if [ -d "$WORKBENCH/$pkg" ]; then
            rm -rf "$WORKBENCH/$pkg"
            echo "  Workbench directory deleted."
        fi
    done

    echo ""
    echo "Done."
}

do_deploy() {
    echo ""
    echo "--- Deploy Packages to Clients ---"
    echo ""

    if ! command -v opsi-admin > /dev/null 2>&1; then
        echo "ERROR: opsi-admin not found."
        return
    fi

    if ! command -v whiptail > /dev/null 2>&1; then
        echo "ERROR: whiptail not found."
        return
    fi

    # Get package list
    echo "Loading packages..."
    pkg_list=$(LC_ALL=C opsi-package-manager -l 2>/dev/null | awk '/^   [a-z0-9]/ {print $1}')

    if [ -z "$pkg_list" ]; then
        echo "No packages found."
        return
    fi

    # Build whiptail checklist for packages
    pkg_count=$(echo "$pkg_list" | wc -l)
    list_height=$pkg_count
    if [ "$list_height" -gt 20 ]; then list_height=20; fi
    height=$((list_height + 8))

    set --
    for pkg in $pkg_list; do
        set -- "$@" "$pkg" "" OFF
    done

    selected_pkgs=$(whiptail --checklist "Select packages (SPACE=select, ENTER=confirm)" $height 60 $list_height "$@" 3>&1 1>&2 2>&3)

    if [ $? -ne 0 ] || [ -z "$selected_pkgs" ]; then
        echo "No packages selected."
        return
    fi

    selected_pkgs=$(echo "$selected_pkgs" | tr -d '"')
    echo ""
    echo "Selected packages:"
    for pkg in $selected_pkgs; do
        echo "  $pkg"
    done

    # Client selection method
    echo ""
    echo "  [1] All clients"
    echo "  [2] Select specific clients"
    echo "  [3] Filter by pattern"
    echo ""
    read -p "Client selection: " client_method

    # Get client list
    echo "Loading clients..."
    client_list=$(LC_ALL=C opsi-admin -d method host_getIdents str '{"type":"OpsiClient"}' 2>/dev/null | tr -d '[]",' | tr ' ' '\n' | sed '/^$/d' | sort)

    if [ -z "$client_list" ]; then
        echo "No clients found."
        return
    fi

    selected_clients=""

    case "$client_method" in
        1)
            selected_clients="$client_list"
            client_count=$(echo "$client_list" | wc -l)
            echo "All $client_count clients selected."
            ;;
        2)
            client_count=$(echo "$client_list" | wc -l)
            clist_height=$client_count
            if [ "$clist_height" -gt 20 ]; then clist_height=20; fi
            cheight=$((clist_height + 8))

            set --
            for client in $client_list; do
                set -- "$@" "$client" "" OFF
            done

            selected_clients=$(whiptail --checklist "Select clients (SPACE=select, ENTER=confirm)" $cheight 70 $clist_height "$@" 3>&1 1>&2 2>&3)

            if [ $? -ne 0 ] || [ -z "$selected_clients" ]; then
                echo "No clients selected."
                return
            fi
            selected_clients=$(echo "$selected_clients" | tr -d '"')
            ;;
        3)
            read -p "Pattern (e.g. raum1 or pc-.*): " pattern
            selected_clients=$(echo "$client_list" | grep -i "$pattern")
            if [ -z "$selected_clients" ]; then
                echo "No clients match pattern."
                return
            fi
            echo "Matching clients:"
            for c in $selected_clients; do
                echo "  $c"
            done
            echo ""
            read -p "Continue? (y/N): " confirm
            if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
                echo "Aborted."
                return
            fi
            ;;
        *)
            echo "Invalid choice."
            return
            ;;
    esac

    if [ -z "$selected_clients" ]; then
        echo "No clients selected."
        return
    fi

    # Confirm
    echo ""
    pkg_num=0
    for _ in $selected_pkgs; do pkg_num=$((pkg_num + 1)); done
    client_num=0
    for _ in $selected_clients; do client_num=$((client_num + 1)); done

    echo "Deploy $pkg_num package(s) to $client_num client(s)?"
    read -p "Proceed? (y/N): " proceed
    if [ "$proceed" != "y" ] && [ "$proceed" != "Y" ]; then
        echo "Aborted."
        return
    fi

    # Set action request
    echo ""
    for pkg in $selected_pkgs; do
        for client in $selected_clients; do
            if LC_ALL=C opsi-admin -d method setProductActionRequest "$pkg" "$client" setup 2>/dev/null; then
                echo "  OK: $pkg -> $client"
            else
                echo "  FAILED: $pkg -> $client"
            fi
        done
    done

    echo ""
    echo "Deploy complete."
}

do_wol() {
    echo ""
    echo "--- Wake-on-LAN ---"
    echo ""

    if ! command -v opsi-admin > /dev/null 2>&1; then
        echo "ERROR: opsi-admin not found."
        return
    fi

    if ! command -v whiptail > /dev/null 2>&1; then
        echo "ERROR: whiptail not found."
        return
    fi

    echo "Loading clients..."
    client_list=$(LC_ALL=C opsi-admin -d method host_getIdents str '{"type":"OpsiClient"}' 2>/dev/null | tr -d '[]",' | tr ' ' '\n' | sed '/^$/d' | sort)

    if [ -z "$client_list" ]; then
        echo "No clients found."
        return
    fi

    echo ""
    echo "  [1] All clients"
    echo "  [2] Select specific clients"
    echo "  [3] Filter by pattern"
    echo ""
    read -p "Client selection: " wol_method

    selected_clients=""

    case "$wol_method" in
        1)
            selected_clients="$client_list"
            ;;
        2)
            client_count=$(echo "$client_list" | wc -l)
            clist_height=$client_count
            if [ "$clist_height" -gt 20 ]; then clist_height=20; fi
            cheight=$((clist_height + 8))

            set --
            for client in $client_list; do
                set -- "$@" "$client" "" OFF
            done

            selected_clients=$(whiptail --checklist "Select clients to wake (SPACE=select, ENTER=confirm)" $cheight 70 $clist_height "$@" 3>&1 1>&2 2>&3)

            if [ $? -ne 0 ] || [ -z "$selected_clients" ]; then
                echo "No clients selected."
                return
            fi
            selected_clients=$(echo "$selected_clients" | tr -d '"')
            ;;
        3)
            read -p "Pattern (e.g. raum1 or pc-.*): " pattern
            selected_clients=$(echo "$client_list" | grep -i "$pattern")
            if [ -z "$selected_clients" ]; then
                echo "No clients match pattern."
                return
            fi
            echo "Matching clients:"
            for c in $selected_clients; do
                echo "  $c"
            done
            echo ""
            read -p "Continue? (y/N): " confirm
            if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
                echo "Aborted."
                return
            fi
            ;;
        *)
            echo "Invalid choice."
            return
            ;;
    esac

    if [ -z "$selected_clients" ]; then
        echo "No clients selected."
        return
    fi

    # Build JSON array of clients
    json_clients="["
    first=1
    for client in $selected_clients; do
        if [ "$first" -eq 1 ]; then
            json_clients="$json_clients\"$client\""
            first=0
        else
            json_clients="$json_clients,\"$client\""
        fi
    done
    json_clients="$json_clients]"

    # Count clients
    client_num=0
    for _ in $selected_clients; do client_num=$((client_num + 1)); done

    echo ""
    echo "Sending Wake-on-LAN to $client_num client(s)..."
    wol_result=$(LC_ALL=C opsi-admin -d method hostControlSafe_start "$json_clients" 2>/dev/null)

    if [ $? -ne 0 ]; then
        echo "WoL failed."
        return
    fi

    # Count sent vs errors
    sent=$(echo "$wol_result" | grep -c '"result": "sent"')
    errors=$(echo "$wol_result" | grep '"error"' | grep -vc 'null')
    echo "WoL packets sent: $sent/$client_num"
    if [ "$errors" -gt 0 ]; then
        echo "Errors: $errors"
        echo "$wol_result" | grep -B2 '"error"' | grep -v 'null' | grep -v '^--$'
    fi

    echo ""
    read -p "Check which clients came online? (y/N): " check_online
    if [ "$check_online" != "y" ] && [ "$check_online" != "Y" ]; then
        return
    fi

    echo ""
    echo "Waiting 60 seconds for clients to boot..."
    sleep 60

    echo "Checking reachability..."
    reach_result=$(LC_ALL=C opsi-admin -d method hostControlSafe_reachable "$json_clients" 2>/dev/null)

    online=0
    offline=0
    online_list=""
    offline_list=""
    for client in $selected_clients; do
        is_online=$(echo "$reach_result" | grep -F "\"$client\"" | grep -c 'true')
        if [ "$is_online" -gt 0 ]; then
            online=$((online + 1))
            online_list="$online_list  ONLINE:  $client
"
        else
            offline=$((offline + 1))
            offline_list="$offline_list  OFFLINE: $client
"
        fi
    done

    if [ -n "$online_list" ]; then
        printf "%s" "$online_list"
    fi
    if [ -n "$offline_list" ]; then
        printf "%s" "$offline_list"
    fi

    echo ""
    echo "Online: $online/$client_num"
    if [ "$offline" -gt 0 ]; then
        echo "Offline: $offline/$client_num"
    fi
}

do_diag() {
    while true; do
        echo ""
        echo "--- Fehleranalyse ---"
        echo ""
        echo "  [1] Fehlgeschlagene Aktionen"
        echo "  [2] Fehlgeschlagene zuruecksetzen"
        echo "  [3] Client-Status pruefen"
        echo "  [4] Client-Logs anzeigen"
        echo "  [5] OPSI-Dienste pruefen"
        echo "  [6] Festplattenplatz"
        echo "  [0] Zurueck"
        echo ""
        read -p "Select: " diag_choice

        case "$diag_choice" in
            1) diag_failed ;;
            2) diag_reset_failed ;;
            3) diag_client ;;
            4) diag_logs ;;
            5) diag_services ;;
            6) diag_disk ;;
            0) return ;;
            *) echo "Invalid choice." ;;
        esac
    done
}

diag_failed() {
    echo ""
    echo "--- Fehlgeschlagene Aktionen ---"
    echo ""

    if ! command -v opsi-admin > /dev/null 2>&1; then
        echo "ERROR: opsi-admin not found."
        return
    fi

    echo "Loading..."
    failed=$(LC_ALL=C opsi-admin -d method productOnClient_getObjects '[]' '{"actionResult":"failed"}' 2>/dev/null)

    if [ -z "$failed" ] || [ "$failed" = "[]" ]; then
        echo "Keine fehlgeschlagenen Aktionen."
        return
    fi

    echo ""
    printf "  %-35s %-30s %s\n" "CLIENT" "PRODUKT" "AKTION"
    echo "  ----------------------------------- ------------------------------ ----------"
    echo "$failed" | awk -F'"' '
        /"clientId"/ { client=$4 }
        /"productId"/ { product=$4 }
        /"lastAction"/ { action=$4; printf "  %-35s %-30s %s\n", client, product, action }
    '
}

diag_reset_failed() {
    echo ""
    echo "--- Fehlgeschlagene zuruecksetzen ---"
    echo ""

    if ! command -v opsi-admin > /dev/null 2>&1; then
        echo "ERROR: opsi-admin not found."
        return
    fi

    echo "Loading..."
    failed=$(LC_ALL=C opsi-admin -d method productOnClient_getObjects '[]' '{"actionResult":"failed"}' 2>/dev/null)

    if [ -z "$failed" ] || [ "$failed" = "[]" ]; then
        echo "Keine fehlgeschlagenen Aktionen."
        return
    fi

    # Show what will be reset and collect pairs
    echo ""
    printf "  %-35s %s\n" "CLIENT" "PRODUKT"
    echo "  ----------------------------------- ------------------------------"
    pairs=$(echo "$failed" | awk -F'"' '
        /"clientId"/ { client=$4 }
        /"productId"/ { product=$4; print client " " product }
    ')
    echo "$pairs" | while read -r client_id product_id; do
        printf "  %-35s %s\n" "$client_id" "$product_id"
    done

    echo ""
    echo "  [1] Alle auf 'setup' setzen (erneut versuchen)"
    echo "  [2] Alle auf 'none' setzen (ignorieren)"
    echo "  [0] Abbrechen"
    echo ""
    read -p "Select: " reset_choice

    case "$reset_choice" in
        1) action="setup" ;;
        2) action="none" ;;
        *) echo "Aborted."; return ;;
    esac

    echo ""
    echo "Setze alle auf '$action'..."

    echo "$pairs" | while read -r client_id product_id; do
        if LC_ALL=C opsi-admin -d method setProductActionRequest "$product_id" "$client_id" "$action" 2>/dev/null; then
            echo "  OK: $product_id -> $client_id ($action)"
        else
            echo "  FAILED: $product_id -> $client_id"
        fi
    done

    echo ""
    echo "Done."
}

diag_client() {
    echo ""
    echo "--- Client-Status ---"
    echo ""

    read -p "Client-ID (e.g. bio-pc01.paedml-linux.lokal): " client_id
    if [ -z "$client_id" ]; then
        echo "Aborted."
        return
    fi

    echo ""
    echo "Loading..."

    # Client info from OPSI
    client_info=$(LC_ALL=C opsi-admin -d method host_getObjects '[]' "{\"id\":\"$client_id\"}" 2>/dev/null)

    if [ -z "$client_info" ] || [ "$client_info" = "[]" ]; then
        echo "Client nicht gefunden: $client_id"
        return
    fi

    echo ""
    echo "Client-Info:"
    ip=$(echo "$client_info" | grep '"ipAddress"' | sed 's/.*: "//;s/".*//')
    mac=$(echo "$client_info" | grep '"hardwareAddress"' | sed 's/.*: "//;s/".*//')
    last_seen=$(echo "$client_info" | grep '"lastSeen"' | sed 's/.*: "//;s/".*//')
    echo "  IP:          ${ip:-unbekannt}"
    echo "  MAC:         ${mac:-unbekannt}"
    echo "  Zuletzt gesehen: ${last_seen:-unbekannt}"

    # Reachability
    echo ""
    echo "Erreichbarkeit:"
    if ping -c 1 -W 2 "$client_id" > /dev/null 2>&1; then
        echo "  ONLINE"
    else
        echo "  OFFLINE"
    fi

    # Pending actions
    echo ""
    echo "Ausstehende Aktionen:"
    pending=$(LC_ALL=C opsi-admin -d method productOnClient_getObjects '[]' "{\"clientId\":\"$client_id\",\"actionRequest\":\"setup\"}" 2>/dev/null)
    if [ -z "$pending" ] || [ "$pending" = "[]" ]; then
        echo "  Keine"
    else
        echo "$pending" | grep '"productId"' | sed 's/.*: "//;s/".*//' | while read -r p; do
            echo "  $p (setup)"
        done
    fi

    # Failed
    echo ""
    echo "Fehlgeschlagen:"
    failed=$(LC_ALL=C opsi-admin -d method productOnClient_getObjects '[]' "{\"clientId\":\"$client_id\",\"actionResult\":\"failed\"}" 2>/dev/null)
    if [ -z "$failed" ] || [ "$failed" = "[]" ]; then
        echo "  Keine"
    else
        echo "$failed" | grep '"productId"' | sed 's/.*: "//;s/".*//' | while read -r p; do
            echo "  $p (FAILED)"
        done
    fi
}

diag_logs() {
    echo ""
    echo "--- Client-Logs ---"
    echo ""

    read -p "Client-ID (e.g. bio-pc01.paedml-linux.lokal): " client_id
    if [ -z "$client_id" ]; then
        echo "Aborted."
        return
    fi

    echo ""
    echo "  [1] Installations-Log (instlog)"
    echo "  [2] Client-Verbindung (clientconnect)"
    echo "  [3] Boot-Image (bootimage)"
    echo ""
    read -p "Log-Typ: " log_choice

    case "$log_choice" in
        1) log_type="instlog" ;;
        2) log_type="clientconnect" ;;
        3) log_type="bootimage" ;;
        *) echo "Invalid choice."; return ;;
    esac

    # Try direct file access first (faster)
    log_file="/var/log/opsi/${log_type}/${client_id}.log"
    if [ -f "$log_file" ]; then
        echo ""
        echo "--- Letzte 50 Zeilen: $log_file ---"
        echo ""
        tail -50 "$log_file"
    else
        echo ""
        echo "Loading via opsi-admin..."
        LC_ALL=C opsi-admin -d method log_read "$log_type" "$client_id" 2>/dev/null | tail -50
    fi
}

diag_services() {
    echo ""
    echo "--- OPSI-Dienste ---"
    echo ""

    for svc in opsiconfd opsipxeconfd; do
        status=$(systemctl is-active "$svc" 2>/dev/null)
        if [ "$status" = "active" ]; then
            echo "  $svc: RUNNING"
        else
            echo "  $svc: $status"
        fi
    done

    echo ""
    echo "opsiconfd Info:"
    if command -v opsiconfd > /dev/null 2>&1; then
        opsiconfd -v 2>/dev/null || echo "  Version nicht ermittelbar"
    fi

    echo ""
    echo "Backend-Verbindung:"
    if LC_ALL=C opsi-admin -d method backend_info > /dev/null 2>&1; then
        echo "  OK"
    else
        echo "  FEHLER"
    fi
}

diag_disk() {
    echo ""
    echo "--- Festplattenplatz ---"
    echo ""

    echo "Depot/Workbench:"
    df -h /var/lib/opsi 2>/dev/null || echo "  /var/lib/opsi nicht gefunden"

    echo ""
    echo "Workbench-Groesse:"
    if [ -d "$WORKBENCH" ]; then
        du -sh "$WORKBENCH" 2>/dev/null
    else
        echo "  Workbench nicht vorhanden"
    fi

    echo ""
    echo "Repository-Groesse:"
    if [ -d "/var/lib/opsi/repository" ]; then
        du -sh /var/lib/opsi/repository 2>/dev/null
    else
        echo "  Repository nicht vorhanden"
    fi
}

do_build() {
    echo ""
    echo "--- Build & Install Package ---"
    echo ""

    if ! command -v opsi-makepackage > /dev/null 2>&1; then
        echo "ERROR: opsi-makepackage not found."
        return
    fi

    if ! command -v whiptail > /dev/null 2>&1; then
        echo "ERROR: whiptail not found."
        return
    fi

    # List workbench packages
    if [ ! -d "$WORKBENCH" ]; then
        echo "Workbench not found: $WORKBENCH"
        return
    fi

    pkg_list=""
    for dir in "$WORKBENCH"/*/; do
        if [ -f "${dir}OPSI/control" ]; then
            pkg_list="$pkg_list $(basename "$dir")"
        fi
    done

    if [ -z "$pkg_list" ]; then
        echo "No packages in workbench."
        return
    fi

    pkg_count=0
    for _ in $pkg_list; do pkg_count=$((pkg_count + 1)); done
    list_height=$pkg_count
    if [ "$list_height" -gt 20 ]; then list_height=20; fi
    height=$((list_height + 8))

    set --
    for pkg in $pkg_list; do
        set -- "$@" "$pkg" "" OFF
    done

    selected_pkgs=$(whiptail --checklist "Select packages to build (SPACE=select, ENTER=confirm)" $height 60 $list_height "$@" 3>&1 1>&2 2>&3)

    if [ $? -ne 0 ] || [ -z "$selected_pkgs" ]; then
        echo "No packages selected."
        return
    fi

    selected_pkgs=$(echo "$selected_pkgs" | tr -d '"')

    for pkg in $selected_pkgs; do
        package_dir="$WORKBENCH/$pkg"

        echo ""
        echo "--- $pkg ---"
        echo "Files in CLIENT_DATA:"
        ls "$package_dir/CLIENT_DATA/" 2>/dev/null
        echo ""

        echo "Building..."
        if (cd "$package_dir" && opsi-makepackage --quiet --no-md5 --no-zsync); then
            echo "Build successful."
        else
            echo "Build failed."
            continue
        fi

        opsi_file=$(ls -t "$package_dir"/*.opsi 2>/dev/null | head -1)
        if [ -z "$opsi_file" ]; then
            echo "ERROR: No .opsi file found."
            continue
        fi

        echo "Installing..."
        if LC_ALL=C opsi-package-manager -i "$opsi_file" 2>/dev/null; then
            echo "Package installed."
        else
            echo "Install failed."
        fi
    done

    echo ""
    echo "Done."
}

do_list() {
    echo ""
    echo "--- Installed OPSI Packages ---"
    echo ""

    if ! command -v opsi-package-manager > /dev/null 2>&1; then
        echo "ERROR: opsi-package-manager not found. Is this the OPSI depot server?"
        return
    fi

    LC_ALL=C opsi-package-manager -l
}

# Main
banner

while true; do
    echo "  [1] Create package"
    echo "  [2] Build package"
    echo "  [3] Remove package"
    echo "  [4] Deploy to clients"
    echo "  [5] Wake-on-LAN"
    echo "  [6] List packages"
    echo "  [7] Fehleranalyse"
    echo "  [0] Exit"
    echo ""
    read -p "Select: " choice

    case "$choice" in
        1) do_create ;;
        2) do_build ;;
        3) do_remove ;;
        4) do_deploy ;;
        5) do_wol ;;
        6) do_list ;;
        7) do_diag ;;
        0) echo "Bye."; exit 0 ;;
        *) echo "Invalid choice." ;;
    esac
done
