#!/bin/bash
# Packforge - CLI tool for creating paedML OPSI packages

WORKBENCH="/var/lib/opsi/workbench"

banner() {
cat << 'EOF'

                      ______ ________
______________ _________  /____  __/___________________ _____
___  __ \  __ `/  ___/_  //_/_  /_ _  __ \_  ___/_  __ `/  _ \
__  /_/ / /_/ // /__ _  ,<  _  __/ / /_/ /  /   _  /_/ //  __/
_  .___/\__,_/ \___/ /_/|_| /_/    \____//_/    _\__, / \___/
/_/                                             /____/

EOF
}

do_create() {
    echo ""
    echo "--- Create OPSI Package ---"
    echo ""

    # Product ID
    while true; do
        read -p "Product ID (e.g. my-software): " product_id
        if echo "$product_id" | grep -qE '^[a-z0-9][a-z0-9-]*$'; then
            break
        fi
        echo "Invalid product ID. Use lowercase letters, numbers, and hyphens."
    done

    # Product name
    read -p "Product name [$product_id]: " product_name
    product_name="${product_name:-$product_id}"

    # Version
    read -p "Version [1.0]: " product_version
    product_version="${product_version:-1.0}"

    # Package version
    read -p "Package version [1]: " package_version
    package_version="${package_version:-1}"

    # Description
    read -p "Description: " description

    # Create directories
    package_dir="$WORKBENCH/$product_id"
    opsi_dir="$package_dir/OPSI"
    client_dir="$package_dir/CLIENT_DATA"

    if [ -d "$package_dir" ]; then
        echo ""
        echo "Directory already exists: $package_dir"
        read -p "Overwrite? (y/N): " overwrite
        if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
            echo "Aborted."
            return
        fi
    fi

    mkdir -p "$opsi_dir" "$client_dir"

    # Write control file
    cat > "$opsi_dir/control" << CTRL
[Package]
version: $package_version
depends:

[Product]
type: localboot
id: $product_id
name: $product_name
description: $description
advice:
version: $product_version
priority: 0
licenseRequired: False
productClasses:
setupScript: setup.ins
uninstallScript: uninstall.ins
updateScript:
alwaysScript:
onceScript:
customScript:
userLoginScript:
CTRL

    # Write setup.ins
    cat > "$client_dir/setup.ins" << SETUP
; setup script for $product_name
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar \$ProductId\$
Set \$ProductId\$ = "$product_id"

Message "Installing " + \$ProductId\$ + " ..."

; Add installation steps here
SETUP

    # Write uninstall.ins
    cat > "$client_dir/uninstall.ins" << UNINST
; uninstall script for $product_name
; generated by Packforge

[Actions]
requiredWinstVersion >= "4.11.4.1"

DefVar \$ProductId\$
Set \$ProductId\$ = "$product_id"

Message "Uninstalling " + \$ProductId\$ + " ..."

; Add uninstallation steps here
UNINST

    echo ""
    echo "Package created: $package_dir"
    echo "  OPSI/control"
    echo "  CLIENT_DATA/setup.ins"
    echo "  CLIENT_DATA/uninstall.ins"
    echo ""

    # Build
    if ! command -v opsi-makepackage > /dev/null 2>&1; then
        echo "ERROR: opsi-makepackage not found."
        return
    fi

    echo "Building package..."
    if (cd "$package_dir" && opsi-makepackage --quiet --no-md5 --no-zsync); then
        echo "Build successful."
    else
        echo "Build failed."
        return
    fi

    # Find the built .opsi file
    opsi_file=$(ls -t "$package_dir"/*.opsi 2>/dev/null | head -1)
    if [ -z "$opsi_file" ]; then
        echo "ERROR: No .opsi file found after build."
        return
    fi

    # Install
    if ! command -v opsi-package-manager > /dev/null 2>&1; then
        echo "ERROR: opsi-package-manager not found."
        return
    fi

    echo "Installing package..."
    if LC_ALL=C opsi-package-manager -i "$opsi_file"; then
        echo "Package installed."
    else
        echo "Install failed."
    fi
}

do_remove() {
    echo ""
    echo "--- Remove OPSI Package ---"
    echo ""

    if ! command -v opsi-package-manager > /dev/null 2>&1; then
        echo "ERROR: opsi-package-manager not found. Is this the OPSI depot server?"
        return
    fi

    read -p "Product ID to remove: " product_id
    if [ -z "$product_id" ]; then
        echo "Aborted."
        return
    fi

    read -p "Are you sure you want to remove '$product_id'? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        return
    fi

    echo "Removing $product_id..."
    if LC_ALL=C opsi-package-manager -r "$product_id"; then
        echo "Package removed."
    else
        echo "Remove failed."
        return
    fi

    # Clean up workbench directory if it exists
    if [ -d "$WORKBENCH/$product_id" ]; then
        read -p "Also delete workbench directory $WORKBENCH/$product_id? (y/N): " cleanup
        if [ "$cleanup" = "y" ] || [ "$cleanup" = "Y" ]; then
            rm -rf "$WORKBENCH/$product_id"
            echo "Workbench directory deleted."
        fi
    fi
}

do_list() {
    echo ""
    echo "--- Installed OPSI Packages ---"
    echo ""

    if ! command -v opsi-package-manager > /dev/null 2>&1; then
        echo "ERROR: opsi-package-manager not found. Is this the OPSI depot server?"
        return
    fi

    LC_ALL=C opsi-package-manager -l
}

# Main
banner

while true; do
    echo "  [1] Create package"
    echo "  [2] Remove package"
    echo "  [3] List packages"
    echo "  [0] Exit"
    echo ""
    read -p "Select: " choice

    case "$choice" in
        1) do_create ;;
        2) do_remove ;;
        3) do_list ;;
        0) echo "Bye."; exit 0 ;;
        *) echo "Invalid choice." ;;
    esac
done
